// Generated by CoffeeScript 1.10.0
var React;

React = require('react');

module.exports = React.createClass({
  displayName: "HTMLWrapper",
  render: function() {
    var html;
    console.log(this.props);
    html = "<div>fix me</div>";
    return (
      <div dangerouslySetInnerHTML={{__html: html}}/>
    );
  }
});
